"""Per-day editorial content for RUDI Daily editions (2026-07-15 onward).

Written by the editorial pass (see the rudi-rundown-writer skill) from the
day's discovery annotation data. Each entry:
  topics   — 3-4 news-forward phrases for the title tag
  dek      — 1-2 sentences; generator appends "All N stories from the day, below."
  modified — dateModified for schema (bump on final-edition republish)
  open     — callable(L) returning paragraph-inner-HTML strings; L(title_substr,
             text) resolves links by unique title substring and FAILS LOUDLY on
             a miss. NO HTML entities inside L() text — use literal — “ ” ’
             characters (entities there double-escape). Entities are fine in the
             raw paragraph strings outside L().
  qa       — list of (question, answer, title_substr_for_source, source_label).

Editions 2026-07-01 .. 2026-07-14 are committed history under their original
rudi-rundown-ai-news-* URLs; their content intentionally does not live here.
"""

DAY = {
"15": {
 "topics": "DeepSeek $71B, Qwen in Apple Intelligence, Publishers v. Google",
 "dek": "DeepSeek reportedly raises at a $71 billion valuation as China's AI boom defies US restrictions, Alibaba's Qwen heads into Apple Intelligence, publishers widen the Google training lawsuit, and South Korea tenders a universal basic AI chatbot.",
 "modified": "2026-07-15",
 "open": lambda L: [
  'China&rsquo;s AI economy had its statement day. ' + L('DeepSeek Races to $71B', 'DeepSeek is reportedly raising $1.5 billion at a $71 billion valuation') + ' ahead of a potential 2027 IPO &mdash; a growth story built while US chip restrictions were supposed to prevent exactly this. ' + L('Qwen to be integrated', 'Alibaba’s Qwen will power Apple Intelligence features in China') + ', per a regulatory filing. And a compression lab showed ' + L('Bonsai 27B', 'a 27-billion-parameter model running locally on an iPhone in under 4GB of memory') + ', retaining about 90% of its performance by its maker&rsquo;s account. The restrictions were the policy; the receipts are the rebuttal.',
  'The watchdog conversation compounded into day two. Coverage of Hassabis&rsquo;s call ' + L('wants US-led global watchdog', 'now frames it against the government’s crackdown on Anthropic’s Mythos models') + ', and a War on the Rocks analysis argued for ' + L('Threat Fusion Center', 'an AI threat fusion center before the next such incident') + '. South Korea went the other direction entirely: ' + L('universal basic AI chatbot', 'a government tender for a universal basic AI chatbot and public-services agent') + ', built on local models with state-provided GPUs. One government wants frontier AI checked before release; another wants it issued like a utility.',
  'The courtroom docket grew again. Publishers&rsquo; ' + L('Publishers Sue Google', 'class action against Google over Gemini training on Google Books titles') + ' now includes, per one report, an internal document warning of billions in exposure. ' + L('Meta Sued For Allegedly', 'Meta faces a suit from 26 former employees alleging its AI layoff tools discriminated') + ' against workers on disability or family leave. And OpenAI, undeterred by its own legal week, is reportedly ' + L('Screenless AI Speaker', 'betting on a screenless AI speaker') + ' as its first hardware act &mdash; a proactive home companion, with all the trust questions that phrase implies.',
 ],
 "qa": [
  ("What is DeepSeek worth now?",
   "DeepSeek is reportedly in talks to raise $1.5 billion at a $71 billion valuation, with an IPO planned for 2027 — a milestone for China's AI sector despite US chip restrictions.",
   "in Talks to Raise $1.5 Billion", "Caproasia"),
  ("Is Apple using Alibaba's Qwen?",
   "In China, yes — a regulatory filing shows Alibaba's Qwen will be integrated into Apple Intelligence to power on-device AI features for Apple devices sold there.",
   "Qwen to be integrated", "TechNode"),
  ("Why are publishers suing Google?",
   "Major publishers allege Google trained Gemini on copyrighted books from Google Books and Google Play without authorization — with one report citing an internal Google document warning of billions in potential exposure.",
   "Publishers Sue Google", "Eastern Herald"),
  ("What is South Korea's universal basic AI chatbot?",
   "South Korea issued a government tender for a universal basic AI chatbot and an AI agent for government services — required to run on local models, with GPUs provided by the state.",
   "universal basic AI chatbot", "The Register"),
  ("Why is Meta being sued over AI layoffs?",
   "Twenty-six former employees allege Meta's AI systems used in layoff decisions discriminated against workers on disability or family leave.",
   "Meta Sued For Allegedly", "Gizmodo"),
  ("Can a serious AI model really run on an iPhone?",
   "PrismML's Bonsai 27B — a compressed 27-billion-parameter model — reportedly runs locally on an iPhone in 3.9GB of memory while retaining roughly 90% of the original model's performance.",
   "Bonsai 27B", "Gigazine"),
  ("Is OpenAI building hardware?",
   "Reportedly yes — a screenless AI speaker positioned as a proactive home companion, facing significant trust and privacy questions before launch.",
   "Screenless AI Speaker", "SquaredTech"),
  ("What is an AI threat fusion center?",
   "A proposed structure for public-private intelligence sharing on advanced AI risks — argued for in a War on the Rocks analysis as the lesson of the Mythos incident, before the next one.",
   "Threat Fusion Center", "War on the Rocks"),
 ],
},
"16": {
 "topics": "Inkling Open Weights, Apple Intelligence in China, Grok 4.5, Hyundai Robot Strike",
 "dek": "Mira Murati's Thinking Machines releases Inkling, a 975-billion-parameter open-weights model, Apple Intelligence wins approval to launch in China with Alibaba and Baidu, SpaceXAI announces Grok 4.5, and Hyundai workers strike over humanoid robots on the line.",
 "modified": "2026-07-20",
 "open": lambda L: [
  'The open-weights frontier got its biggest American entry yet: Mira Murati&rsquo;s Thinking Machines Lab released ' + L('Former OpenAI CTO', 'Inkling, a 975-billion-parameter model under Apache 2.0') + ', aimed &mdash; by The Register&rsquo;s reading &mdash; at the Chinese open models that have set that category&rsquo;s pace. SpaceXAI ' + L('Introducing Grok 4.5', 'announced Grok 4.5') + ', pitched by its maker for coding, agentic tasks, and knowledge work. A daily roundup adds ' + L('Kimi K3 surpasses', 'Moonshot launching Kimi K3 at 2.8 trillion parameters') + ' to the same news cycle. Google supplied the counterpoint: per one report, its rebuilt Gemini 3.5 Pro ' + L('Misses Third Deadline', 'missed a third launch deadline') + ' over persistent hallucinations, with a stopgap release under consideration. The frontier is getting more open and more crowded while one of its incumbents slips.',
  'Governments spent the day redrawing access lines. Apple Intelligence ' + L('Apple Intelligence approved', 'won approval to launch in China') + ' with Alibaba&rsquo;s Qwen and Baidu aboard &mdash; confirmation of the filing that surfaced a day earlier. The US Commerce Department, per one report, ' + L('UAE Gets License-Free', 'reclassified the UAE to a trusted trade tier') + ', clearing license-free Nvidia chip exports for the Stargate project even as Congress probes a related crypto conflict. Washington is also ' + L('Triggers Washington', 'scrutinizing GLM-5.2') + ', the Chinese model now driving policy debates on safety and security. And Australia went the other direction on training data: Prime Minister Albanese ' + L('Rejects AI Copyright', 'called unlicensed training on copyrighted work theft') + ', ruled out a text-and-data-mining exception, and promised legislation &mdash; a stance one report says could complicate Anthropic&rsquo;s reported $21.6 billion investment in the country.',
  'The robots expanded their footprint and met resistance on the same day. NVIDIA announced Cosmos 3 Edge alongside ' + L('Robotics and Manufacturing Leaders', 'Japanese robotics and manufacturing partners') + ', and Japan&rsquo;s healthcare giants are ' + L('AI Into Surgery', 'putting AI into surgical robots, CT scanners, and drug discovery') + ', with several products already shipping. On the factory floor, Hyundai workers in South Korea ' + L('Hyundai Factory Workers Strike', 'went on strike over humanoid robots') + ' &mdash; one report says the deployment came without union consultation and hit production of 5,000 vehicles; ' + L('Labor Union Is in Revolt', 'another frames the dispute') + ' around wages and safeguards against job losses to Boston Dynamics machines. The accounts differ on emphasis; the trigger &mdash; robots on the line &mdash; doesn&rsquo;t. Upstream, server maker Inventec ' + L('Inventec Warns', 'warns component lead times have passed 40 weeks') + ' as AI demand reallocates memory and CPU capacity.',
 ],
 "qa": [
  ("What is Inkling, the new AI model from Mira Murati?",
   "Inkling is a 975-billion-parameter open-weights model released by Murati's Thinking Machines Lab under an Apache 2.0 license — positioned, per The Register, to compete with the Chinese frontier models leading the open category.",
   "Former OpenAI CTO", "The Register"),
  ("Is Apple Intelligence launching in China?",
   "Yes. Apple Intelligence received regulatory approval to launch in China through partnerships with Alibaba's Qwen and Baidu.",
   "Apple Intelligence approved", "TechCrunch"),
  ("What is Grok 4.5?",
   "SpaceXAI's newly announced model, optimized — by its maker's account — for coding, agentic tasks, and knowledge work, with competitive performance and pricing claims.",
   "Introducing Grok 4.5", "SpaceXAI"),
  ("Is Gemini 3.5 Pro delayed again?",
   "Per one report, yes — the rebuilt model has missed its third launch deadline over persistent hallucinations and inconsistent output, and Google is said to be exploring a stopgap release.",
   "Misses Third Deadline", "Tech Times"),
  ("Why are Hyundai factory workers on strike?",
   "Over humanoid robots. One report says Hyundai deployed them without union consultation, affecting production of 5,000 vehicles; another describes a fight over wages plus safeguards against job losses to Boston Dynamics robots.",
   "Labor Union Is in Revolt", "Gizmodo"),
  ("Did Australia ban AI training on copyrighted material?",
   "Australia's prime minister called unlicensed AI training theft and confirmed there will be no text-and-data-mining exception, with new legislation planned — a stance one report says could affect Anthropic's reported $21.6 billion investment.",
   "Rejects AI Copyright", "Tech Times"),
  ("Are AI chatbots spreading government censorship?",
   "A new study — attributed in one report to Meta's Oversight Board — found major chatbots are more likely to refuse to criticize restrictive governments, which researchers warn risks extending state speech controls globally.",
   "AI chatbots are at risk", "OC Register"),
  ("Does Geoffrey Hinton think AI is conscious?",
   "Yes — on the Big Technology Podcast he argued current AI systems are already conscious, and that corporate fiduciary duties overriding safety commitments make the risk structural and present rather than future.",
   "Geoffrey Hinton", "Tech Times"),
 ],
},
"17": {
 "topics": "White House Model Access, Gemini 3.5 Pro Conflict, Kimi K3, Xi's 29-Nation AI Alliance",
 "dek": "Sources tell CNBC the White House now decides who gets access to frontier models from Anthropic and OpenAI, Xi Jinping launches a 29-nation AI alliance in Shanghai, reports conflict on whether Gemini 3.5 Pro launched or slipped months, and Moonshot's 2.8-trillion-parameter Kimi K3 goes open weights.",
 "modified": "2026-07-20",
 "open": lambda L: [
  'Who gets frontier AI became a government question on both sides of the Pacific. Sources tell CNBC the Trump administration is now ' + L('dictating access', 'deciding which companies and entities can access advanced models') + ' from Anthropic and OpenAI &mdash; moving a gate that used to belong to the labs. Some of the industry asked for a version of this: one account describes ' + L('the Labs Asked for It', 'labs actively requesting regulation') + ' after voluntary safety failures, down to a proposed FINRA-like oversight body, while the White House stands up its Gold Eagle security program. The same day in Shanghai, Xi Jinping ' + L('launches new AI alliance', 'launched WAICO, a 29-nation AI cooperation organization') + ', framed explicitly against US efforts to check China&rsquo;s AI development. Europe&rsquo;s dates firmed up too: the Digital Omnibus ' + L('What Actually Applies on 2 August', 'pushes high-risk obligations to late 2027 and 2028') + ', while Article 50 transparency duties land August 2. Three capitals, three different answers to who sets the terms.',
  'Google had the kind of day that produces contradictory headlines. The Los Angeles Times describes Gemini 3.5 Pro ' + L('coding stumbles', 'months behind schedule amid coding stumbles, clashing teams, and frustrated engineers') + '; a markets piece ties ' + L('Sparks Market Concerns', 'the delay to a stock drop') + ' and doubts about Google&rsquo;s standing in AI programming; and one outlet reports Google ' + L('Launches Gemini 3.5 Pro', 'released Gemini 3.5 Pro the same day Xi opened the Shanghai summit') + '. Delayed by months and launched the same day &mdash; the reports conflict; what&rsquo;s consistent across them is a flagship badly off schedule. The rest of the field moved while Google wobbled: Moonshot released ' + L('Kimi K3: world', 'Kimi K3, a 2.8-trillion-parameter open-weight model') + ' its coverage describes as approaching Anthropic&rsquo;s Fable; Berlin&rsquo;s Prior Labs ' + L('Prior Labs raises', 'raised €1 billion and exited to SAP') + ' eighteen months after founding; and chip stocks ' + L('AMD Falls 5%', 'slid in a rotation') + ' one report pins partly on AI cost worries &mdash; AMD down 5%, Intel 4%, Nvidia 3% before a partial recovery.',
  'The courts spent the day assigning responsibility. Apple ' + L('Legal Letters to Dozens', 'sent preservation letters to 40 former employees now at OpenAI') + ' as part of its trade-secret lawsuit. Bloomberg Law reports ' + L('Shareholder Suits', 'a new wave of shareholder derivative suits') + ' accusing Big Tech executives of concealing illicit training on copyrighted material &mdash; the copyright fight arriving on the fiduciary-duty docket. San Francisco&rsquo;s city attorney ' + L('Nudify', 'demanded Apple and Google pull 13 nudify apps') + ' that generate nonconsensual deepfake images. Kaiser nurses say ' + L('Kaiser nurses', 'AI surveillance and call-time metrics are making patient care worse') + ' as contract negotiations approach. And Anthropic ' + L('Claude for Teachers', 'launched a free Claude for Teachers') + ' with the Chan Zuckerberg Initiative &mdash; drawing immediate questions about de-skilling the profession it&rsquo;s courting.',
 ],
 "qa": [
  ("Is the White House deciding who can access frontier AI models?",
   "According to sources cited by CNBC, yes — the administration is taking control over which companies and entities can access advanced models from Anthropic and OpenAI, shifting that power from the labs to the government.",
   "dictating access", "CNBC"),
  ("Is Gemini 3.5 Pro released or delayed?",
   "Reports conflict. The LA Times describes a model months behind schedule amid internal friction, and a markets piece ties the delay to a stock drop — while one outlet says Google released it the same day as Xi Jinping's Shanghai keynote. What's consistent: the schedule slipped badly.",
   "coding stumbles", "LA Times"),
  ("What is Kimi K3?",
   "Moonshot's 2.8-trillion-parameter open-weight model — described in its coverage as the world's largest open model, with performance approaching Anthropic's Fable.",
   "Kimi K3: world", "ResultSense"),
  ("What is WAICO, China's new AI alliance?",
   "A 29-nation AI cooperation organization launched by Xi Jinping, with China calling for international cooperation and opposing US attempts to stymie its AI development.",
   "launches new AI alliance", "Al Jazeera"),
  ("What EU AI Act rules take effect on August 2, 2026?",
   "Article 50 transparency rules — covering chatbots, deepfakes, and AI-generated content — apply on August 2, while the Digital Omnibus delays high-risk obligations to December 2027 or August 2028.",
   "What Actually Applies on 2 August", "Technology Org"),
  ("Why is Apple sending legal letters to OpenAI employees?",
   "Apple sent preservation letters to 40 former employees now at OpenAI as part of its trade-secret lawsuit against the company.",
   "Legal Letters to Dozens", "MacRumors"),
  ("What is Claude for Teachers?",
   "A free teacher version of Claude launched by Anthropic in partnership with the Chan Zuckerberg Initiative — with critics questioning its value and warning about de-skilling teachers.",
   "Claude for Teachers", "EdWeek"),
  ("Why did chip stocks fall?",
   "A risk-off rotation hit semiconductors, with one report citing AI cost worries — AMD fell 5%, Intel 4%, and Nvidia 3% before a partial recovery.",
   "AMD Falls 5%", "24/7 Wall St."),
 ],
},
"18": {
 "topics": "Claude Fable 5 Pricing, Meta Layoff Ruling, 84% Agent Concentration, Etched at $20B",
 "dek": "Anthropic makes Claude Fable 5 permanent for Max subscribers while Pro users get a credit then API pricing, a US judge declines to block Meta from laying off workers who sued over AI discrimination, France's competition authority flags three companies holding 84% of the AI agent market, and Etched chases a $20 billion valuation on $1 billion in pre-ship demand.",
 "modified": "2026-07-20",
 "open": lambda L: [
  'Saturday&rsquo;s theme was the bill. Anthropic, per one report, made ' + L('Ends Subscription Limbo', 'Claude Fable 5 permanent for Max and Team Premium subscribers') + ' at reduced limits, while Pro users get a one-time usage credit and then API pricing. France&rsquo;s competition authority put a number on the market those prices live in: OpenAI, Google, and Anthropic ' + L('France flags lock-in', 'hold 84% of the AI agent market') + ', and the regulator wants data-access and interoperability rules before lock-in hardens. Investors keep paying in advance regardless: inference-chip startup Etched is ' + L('Etched targets', 'running back-to-back rounds at $10 billion and $20 billion valuations') + ', backed by a reported $1 billion in customer demand for a chip that hasn&rsquo;t shipped. And McKinsey supplied the quiet stat of the day: as enterprises scale agents, ' + L('ROI test', 'nearly 60% of operating costs go to verification') + ' &mdash; paying people and systems to check the machines&rsquo; work.',
  'A US judge ' + L('U.S. judge won', 'declined to block Meta from laying off 26 workers') + ' who allege the company&rsquo;s AI tools discriminated against employees with disabilities or on medical leave &mdash; the discrimination suit continues, but the layoffs proceed. The year&rsquo;s broader tally, by one count: ' + L('Nearly 40 companies', 'more than 165,000 people laid off across nearly 40 companies') + ' with AI adoption cited as the primary driver. A separate analysis describes ' + L('Entry-Level Work Statistics', 'career-ladder compression') + ', with junior roles splitting into seniorized tracks and declining ones. And a workplace-consent gap got measured: only 35% of workers say they are ' + L('always asked', 'always asked before AI transcribes their meetings') + '.',
  'Governance did not take the weekend off. Brazil&rsquo;s electoral court ' + L('Brazil TSE adds', 'added OpenAI, Anthropic, and ElevenLabs to its election disinformation pact') + ' ahead of the 2026 vote, extending deepfake rules from platforms to the model vendors themselves. One analysis reads the WAIC chair&rsquo;s statement as ' + L('Global AI Governance', 'a Chinese bid to write global AI governance rules') + '. The scam economy moved faster than the policy: fraudsters are ' + L('Gold Eagle', 'impersonating the White House Gold Eagle security initiative') + ' to harvest credentials from financial institutions, and a post-mortem ' + L('JadePuffer', 'examines the JadePuffer ransomware and its autonomy claims') + ' alongside the industry pushback it provoked. The EU&rsquo;s Article 50 transparency duties ' + L('What Actually Applies From August', 'still arrive on August 2') + ', omnibus delay or not.',
 ],
 "qa": [
  ("Is Claude Fable 5 staying available?",
   "Per one report, yes for some tiers — Anthropic made Fable 5 permanent for Max and Team Premium subscribers at reduced limits, while Pro users get a one-time usage credit before being pointed to API pricing.",
   "Ends Subscription Limbo", "Tech Times"),
  ("Did Meta win the AI discrimination lawsuit?",
   "No — but a US judge declined to block Meta from laying off the 26 workers who brought it, so the layoffs proceed while the discrimination claims continue.",
   "U.S. judge won", "The Hindu"),
  ("How concentrated is the AI agent market?",
   "France's competition authority says OpenAI, Google, and Anthropic control 84% of it, and is urging regulatory action on data access and interoperability to prevent lock-in.",
   "France flags lock-in", "PPC Land"),
  ("What is Etched worth now?",
   "The inference-chip startup is pursuing two concurrent rounds at $10 billion and $20 billion valuations, backed by a reported $1 billion in customer demand for a product that has not yet shipped.",
   "Etched targets", "MarketScale"),
  ("Is AI killing entry-level jobs?",
   "2026 data shows career-ladder compression — junior roles splitting into seniorized and declining categories — and a separate count attributes layoffs of more than 165,000 people across nearly 40 companies primarily to AI adoption.",
   "Entry-Level Work Statistics", "Memeburn"),
  ("What is the JadePuffer ransomware?",
   "A ransomware incident exploiting CVE-2025-3248, notable for claims about the malware's autonomy — an analysis examines those claims, the industry pushback, and the regulatory implications.",
   "JadePuffer", "Tech Insider"),
  ("Is the White House Gold Eagle program a scam?",
   "The initiative itself is legitimate — but one analysis documents scammers impersonating it to run credential-harvesting attacks against financial institutions.",
   "Gold Eagle", "Unbox Future"),
  ("What does Brazil's election AI pact require?",
   "Brazil's Superior Electoral Court added OpenAI, Anthropic, and ElevenLabs to its election disinformation pact, enforcing strict rules against deepfakes and synthetic content ahead of the 2026 elections.",
   "Brazil TSE adds", "The Rio Times"),
 ],
},
"19": {
 "topics": "Qwen 3.8 at 2.4T, Australia Government AI Rules, Russia's AI Law, 88% Teacher Adoption",
 "dek": "Alibaba announces Qwen 3.8 at 2.4 trillion parameters — second only to Fable 5, by its own account — Australia moves to curb automated government decision-making, Russia's Federation Council approves a framework AI law, and 88% of teachers now use ChatGPT while only a third of districts have AI rules.",
 "modified": "2026-07-20",
 "open": lambda L: [
  'Alibaba took Sunday. It announced ' + L('Launches Qwen 3.8', 'Qwen 3.8, a 2.4-trillion-parameter multimodal model') + ' with preview pricing at 10% of standard rates and an open-weight release promised &mdash; and performance that is, ' + L('According to Alibaba', 'by its own account') + ', second only to Anthropic&rsquo;s Fable 5. That is vendor math, worth reading as such until the weights ship. The rest of the model race filled in around it: an analysis piece describes ' + L('What Is Grok 4.6', 'Grok 4.6 as a 2-trillion-parameter model targeting Kimi K3 capability at Grok 4.5 speed') + ', OpenAI has, per one report, ' + L('Starts Billing', 'started billing for agents') + ' while its ' + L('ChatGPT Work', 'ChatGPT Work mode') + ' folds multi-step agent tasks into existing subscriptions, and one infrastructure analysis argues the competition has moved to ' + L('100,000-GPU', '100,000-GPU systems') + ' &mdash; networking, power, cooling, and reliability rather than chips.',
  'Governments regulated on a Sunday. Australia will ' + L('decision-making to be curbed', 'curb automated AI decision-making in government') + ', packaged with a digital duty of care and privacy reforms &mdash; ' + L('Labor to tighten rules', 'a response, per one report, to past automated errors') + '. Russia&rsquo;s Federation Council ' + L('Совет Федерации', 'approved a framework AI law') + ' that creates categories for sovereign and national models and requires labeling of AI-generated content. Coverage of the publishers&rsquo; ' + L('Publishers Sue Google', 'copyright suit against Google over Gemini training') + ' kept spreading. And China ' + L('MIZZIMA', 'declined to apologize for a state-media AI video mocking Filipinos') + ', folding an AI-content dispute into its South China Sea position.',
  'The adoption-governance gap got a number: ' + L('88% of Teachers', '88% of teachers use ChatGPT while only one in three districts has AI rules') + '. India&rsquo;s market regulator warned of the ' + L('Boss Scam', 'boss scam: AI voice clones and fake CEO messages') + ' aimed at finance employees. One analysis reframes the ' + L('Data Center Backlash', 'data-center backlash as a capacity-planning problem') + ' for enterprises, not just hyperscalers &mdash; state restrictions and local activism now translate into cost and siting risk. And the Meta layoffs ruling got its reasoning in second-day coverage: the plaintiffs ' + L('Rejects Bid to Halt', 'failed to show irreparable harm') + ', so the layoffs proceed while the discrimination suit continues.',
 ],
 "qa": [
  ("What is Qwen 3.8?",
   "Alibaba's newly announced 2.4-trillion-parameter multimodal model, offered at preview pricing of 10% of standard rates with an open-weight release promised.",
   "Launches Qwen 3.8", "MLQ News"),
  ("Is Qwen 3.8 better than Fable 5?",
   "Alibaba itself says no — it claims Qwen 3.8 is second only to Anthropic's Fable 5. That is a vendor claim about an unreleased set of weights, worth reading skeptically until independent benchmarks exist.",
   "According to Alibaba", "El Solitario"),
  ("What is Grok 4.6?",
   "Per one analysis, a 2-trillion-parameter xAI frontier model targeting Kimi K3 capability at Grok 4.5 speed.",
   "What Is Grok 4.6", "Kie.ai"),
  ("What are Australia's new government AI rules?",
   "Australia announced rules restricting automated AI decision-making in government, alongside a digital duty of care, privacy reforms, and AI workplace-safety plans — a response one report ties to past automated errors.",
   "decision-making to be curbed", "The Guardian"),
  ("Why did a judge let Meta's AI-driven layoffs proceed?",
   "The judge ruled the workers failed to show irreparable harm, denying an emergency injunction — the layoffs proceed while their AI-bias discrimination claims continue.",
   "Rejects Bid to Halt", "Mathrubhumi"),
  ("What is Russia's new AI law?",
   "A framework law approved by the Federation Council establishing permanent legal conditions for AI development — including categories for sovereign and national AI models, support measures for developers, and labeling requirements for AI-generated content.",
   "Совет Федерации", "Rossiyskaya Gazeta"),
  ("What is the AI boss scam?",
   "A fraud pattern flagged by India's market regulator SEBI: attackers use AI voice clones and fake CEO messages to pressure finance employees into transferring money.",
   "Boss Scam", "Sangri Times"),
  ("Do schools have rules for AI use?",
   "Mostly not yet — a survey finds 88% of teachers use ChatGPT while only one in three districts has an AI policy.",
   "88% of Teachers", "Windows News"),
 ],
},
"20": {
 "topics": "AMD Helios Delivery, Illinois AI Safety Act, Copilot Cowork Credits, AI Search at 50%",
 "dek": "AMD's first rack-scale AI system Helios heads for delivery with Microsoft as its newest customer, Illinois enacts frontier-model safety legislation, Microsoft turns Copilot Cowork into a credit-metered agent, and McKinsey finds half of consumer product research now starts in AI search.",
 "modified": "2026-07-20",
 "open": lambda L: [
  'AMD put hardware behind years of talk about challenging Nvidia. Its first rack-scale AI system, Helios, ' + L('AMD launches Helios', 'is headed for delivery with Microsoft as its newest customer') + ', joining Meta, OpenAI, and Oracle on the buyer list. ' + L('Shares Rise More Than 3%', 'AMD shares rose more than 3%') + ', and one report calls Helios the first strong rival Nvidia has faced in years &mdash; a judgment deliveries, not announcements, will settle.',
  'The governance ledger ran from statehouse to street. Illinois ' + L('Illinois Enacts', 'enacted an AI Safety Measures Act') + ' imposing governance, transparency, audit, and incident-reporting obligations on developers of advanced frontier models &mdash; a state law reaching directly into the frontier tier. At the UN, leaders argue ' + L('Cannot Wait', 'global AI governance cannot wait') + ' as the digital divide widens, pressing for guardrails and capacity building in developing countries. And Vox examines ' + L('populist protests', 'the rise of AI populism') + ' &mdash; protests, and in some cases violence, aimed at AI and data centers, driven by anger over corporate power exercised without democratic input.',
  'The agent economy started metering. Microsoft&rsquo;s ' + L('Copilot Cowork is Now', 'Copilot Cowork is now a metered agent that consumes credits') + ' as it rolls out globally, with admin controls for deployment and spending. xAI shipped ' + L('Grok for Excel', 'a free Grok for Excel add-in') + ' powered by Grok 4.5. SAP&rsquo;s quarter ' + L('Release Highlights', 'stacked Joule Work, an Autonomous Suite, and Industry AI') + '. The demand side explains the urgency: McKinsey finds ' + L('AI Search Now Starts Half', 'half of consumers now start product research in AI search') + ', which moves brands from chasing rankings to chasing citations. And in the lab, a survey of biopharma executives credits AI with ' + L('Supercharging Drug Development', 'cutting early drug-development costs and timelines by up to 70%') + '.',
 ],
 "qa": [
  ("What is AMD Helios?",
   "AMD's first rack-scale AI system, now set for delivery — a direct challenge to Nvidia's dominance in data-center AI, with Microsoft, Meta, OpenAI, and Oracle as customers.",
   "AMD launches Helios", "CNBC"),
  ("Who is buying AMD's Helios system?",
   "Microsoft is the newest early customer, joining Meta, OpenAI, and Oracle.",
   "Microsoft backs AMD Helios", "Hindustan Times"),
  ("What does the Illinois AI Safety Measures Act do?",
   "It imposes governance, transparency, audit, and incident-reporting obligations on developers of advanced frontier AI models.",
   "Illinois Enacts", "Mondaq"),
  ("What is Copilot Cowork?",
   "Microsoft's agent product, now rolled out globally as a metered agent that consumes credits based on usage, with admin controls for deployment and spending.",
   "Copilot Cowork is Now", "WinBuzzer"),
  ("Is there a Grok add-in for Excel?",
   "Yes — xAI released a free Grok for Excel add-in powered by Grok 4.5, for natural-language data analysis, modeling, and charting inside Excel.",
   "Grok for Excel", "Basenor"),
  ("Do people really start shopping research with AI now?",
   "A McKinsey survey finds half of consumers now begin product research with AI search tools — pushing brands to prioritize authoritative, citable content over SEO volume.",
   "AI Search Now Starts Half", "Influencers Time"),
  ("Is AI actually making drug development cheaper?",
   "A survey of biopharma executives credits AI tools with cutting preclinical drug-development costs and timelines by up to 70%.",
   "Supercharging Drug Development", "IBTimes"),
  ("Why are people protesting AI data centers?",
   "A Vox examination describes rising AI populism — protests and in some cases violence against AI and data centers, reflecting public anger over corporate power and the lack of democratic input.",
   "populist protests", "Vox"),
 ],
},
}
